{
 "title": "kafka-topic-operator",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kubernetes_namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "operator state",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "repeat": "namespace",
   "targets": [
    { "expr": "operator_state" }
   ]
  },
  {
   "title": "Number Of Topics Managed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 1 },
   "targets": [
    { "expr": "managed_topics" }
   ]
  },
  {
   "title": "Topic Managed status",
   "type": "table",
   "gridPos": { "h": 21, "w": 13, "x": 0, "y": 8 },
   "targets": [
    { "expr": "managed_topic  " }
   ]
  }
 ]
}