id: kafka-topic-operator
kind: Template
apiVersion: v1
name: kafka-topic-operator
metadata:
  name: kafka-topic-operator
  label:
    app: kafka-topic-operator
    approle: operator
    category: messaging
  annotations:
    description: Create Kafka operator
    tags: kafka,messaging
    openshift.io/display-name: Kafka Topic Operator
    iconClass: fa pficon-topology
parameters:
- description: Kafka Bootstrap Servers address
  displayName: Kafka Bootstrap Server
  name: BOOTSTRAP_SERVERS
  value: 'kafka:9092'
  required: true
- description: Default replication factor for kafka topics
  displayName: Default replication factor
  name: DEFAULT_REPLICATION_FACTOR
  value: '1'
  required: false
- description: Set to 'true' to enable deletion of kafka topics managed by operator. 
  displayName: Enable topic delete
  name: ENABLE_TOPIC_DELETE
  value: 'false'
  required: false
- description: Set to 'true' to import and start managing existing topics 
  displayName: Import existing topics
  name: ENABLE_TOPIC_IMPORT
  value: 'false'
  required: false
- description: If set to true activates acl managment
  displayName: Enable ACL  
  name: ENABLE_ACL
  value: 'false'
  required: false
- description: Set log level (debug|info|warn|error)
  displayName: Operator log level 
  name: LOG_LEVEL
  value: 'debug'
  required: false
- description: Set JVM resources
  displayName: JAVA Options 
  name: JAVA_OPTIONS
  value: '-Xmx256M'
  required: false
- description: Unique id of the operator in a namespace
  displayName: Operator ID 
  name: OPERATOR_ID
  value: 'kafka-topic-operator'
  required: false
- description: Set Kafka timeout
  displayName: Kafka timeout (ms) 
  name: KAFKA_TIMEOUT_MS
  value: '30000'
  required: false
- description: HTTP port to expose metrics
  displayName: Metrics port
  name: METRICS_PORT
  value: '9889'
  required: false
- description: METRICS JVM
  displayName: METRICS_JVM
  name: METRICS_JVM
  value: '9779'
  required: false
- description: HTTP port for health check endpoints
  displayName: Healths port
  name: HEALTHS_PORT
  value: '9559'
- description: The maximum allowed value of replication factor
  displayName: Max Replication Factor
  name: MAX_REPLICATION_FACTOR
  value: '3'
  required: false
- description: The maximum allowed value of topic partitions
  displayName: Max topic partitions
  name: MAX_PARTITIONS
  value: '2000'
  required: false
- description: The maximum allowed value of topic retention in Ms
  displayName: Max topic retention (ms) 
  name: MAX_RETENTION_MS
  value: '604800000'
  required: false


objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: kafka-topic-operator
    label:
      app: kafka-topic-operator
      approle: operator
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: kafka-topic-operator
    label:
      app: kafka-topic-operator
      approle: operator
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: kafka-topic-operator
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: kafka-topic-operator
    label:
      app: kafka-topic-operator
      approle: operator
  spec:
    dockerImageRepository: nbogojevic/kafka-operator
    tags:
      - name: latest
        importPolicy: 
          scheduled: true
        from:
          kind: DockerImage
          name: >-
            nbogojevic/kafka-operator:latest

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: kafka-topic-operator
    label:
      app: kafka-topic-operator
      approle: operator
  spec:
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - kafka-topic-operator
          from:
            kind: ImageStreamTag
            name: nbogojevic/kafka-operator:latest
      - type: ConfigChange
    replicas: 1
    selector:
      deploymentconfig: kafka-topic-operator
    template:
      metadata:
        labels:
          app: kafka-topic-operator
          deploymentconfig: kafka-topic-operator
      spec:
        containers:
          - name: kafka-topic-operator
            image: nbogojevic/kafka-operator
            ports:
              - name: prometheus
                containerPort: 9889
                protocol: TCP
              - containerPort: 9779
                name: METRICS_JVM
                protocol: TCP
              - containerPort: 9559
                name: healthz
                protocol: TCP
            env:
              - name: BOOTSTRAP_SERVERS
                value: "${BOOTSTRAP_SERVERS}"
              - name: DEFAULT_REPLICATION_FACTOR
                value: ${DEFAULT_REPLICATION_FACTOR}
              - name: ENABLE_TOPIC_DELETE
                value: ${ENABLE_TOPIC_DELETE}
              - name: ENABLE_TOPIC_IMPORT
                value: ${ENABLE_TOPIC_IMPORT}
              - name: ENABLE_ACL
                value: ${ENABLE_ACL}
              - name: LOG_LEVEL
                value: "${LOG_LEVEL}"
              - name: JAVA_OPTIONS
                value: "${JAVA_OPTIONS}"
              - name: OPERATOR_ID
                value: "${OPERATOR_ID}" 
              - name: KAFKA_TIMEOUT_MS
                value: ${KAFKA_TIMEOUT_MS}
              - name: METRICS_PORT
                value: ${METRICS_PORT}
              - name: METRICS_JVM
                value: ${METRICS_JVM}
              - name: MAX_REPLICATION_FACTOR
                value: ${MAX_REPLICATION_FACTOR}
              - name: MAX_PARTITIONS
                value: ${MAX_PARTITIONS}
              - name: MAX_RETENTION_MS
                value: ${MAX_RETENTION_MS}
                readinessProbe:
                  httpGet:
                    path: /ready
                    port: healthz
                  initialDelaySeconds: 15
                  timeoutSeconds: 1
                  livenessProbe:
                    httpGet:
                      path: /healthy
                      port: healthz
                    initialDelaySeconds: 15
                    timeoutSeconds: 1
                  resources:
                    limits:
                      memory: 300Mi
                    requests:
                      memory: 150Mi
            terminationMessagePath: /dev/termination-log
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        serviceAccountName: kafka-topic-operator
        serviceAccount: kafka-topic-operator
        dnsPolicy: ClusterFirst
            