apiVersion: v1
kind: Service
metadata:
  name: kafka-topic-operator
  namespace: kafkaoperator
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path:   /
    prometheus.io/port:   '8080'
spec:
  selector: 
    app: kafka-topic-operator
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090 
      
